# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/user/verilog600/verilog6_sample.cache/wt [current_project]
set_property parent.project_path C:/Users/user/verilog600/verilog6_sample.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/user/lab6/lab6_template/template/ip [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/user/verilog600/verilog6_sample.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/user/lab6/lab6_template/template/SampleCode_VGA/Pictrans/kanahei.coe
add_files C:/Users/user/lab6/lab6_template/template/SampleCode_VGA/Pictrans/rumble.coe
add_files C:/Users/user/lab6/lab6_template/template/SampleCode_VGA/Pictrans/XDD.coe
add_files C:/Users/user/lab6/lab6_template/template/SampleCode_VGA/Pictrans/lion.coe
add_files c:/Users/user/SampleCode_VGA/Pictrans/bigyo.coe
read_verilog -library xil_defaultlib {
  C:/Users/user/verilog600/verilog6_sample.srcs/sources_1/imports/demo2/clock_divider.v
  C:/Users/user/verilog600/verilog6_sample.srcs/sources_1/imports/template/debounce.v
  C:/Users/user/verilog600/verilog6_sample.srcs/sources_1/imports/demo2/mem_addr_gen.v
  C:/Users/user/verilog600/verilog6_sample.srcs/sources_1/imports/template/one_pulse.v
  C:/Users/user/verilog600/verilog6_sample.srcs/sources_1/imports/demo2/vga.v
  C:/Users/user/verilog600/verilog6_sample.srcs/sources_1/imports/template/lab6_1.v
}
read_ip -quiet C:/Users/user/verilog600/verilog6_sample.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/user/verilog600/verilog6_sample.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/user/verilog600/verilog6_sample.srcs/constrs_1/imports/demo1/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/user/verilog600/verilog6_sample.srcs/constrs_1/imports/demo1/Basys3_Master.xdc]

read_xdc C:/Users/user/verilog600/verilog6_sample.srcs/constrs_1/imports/template/lab6_1.xdc
set_property used_in_implementation false [get_files C:/Users/user/verilog600/verilog6_sample.srcs/constrs_1/imports/template/lab6_1.xdc]

read_xdc C:/Users/user/verilog600/verilog6_sample.srcs/constrs_1/imports/template/lab6_2.xdc
set_property used_in_implementation false [get_files C:/Users/user/verilog600/verilog6_sample.srcs/constrs_1/imports/template/lab6_2.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top lab6_1 -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef lab6_1.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file lab6_1_utilization_synth.rpt -pb lab6_1_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
